name: CI_build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest
    strategy:
      max-parallel: 6
      matrix:
        build_configuration: [Release, Debug]
        build_platform: [x64, Win32]

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: MSBuild of application exe
      working-directory: StayAwake
      run: msbuild StayAwake.vcxproj /m /p:configuration="${{ matrix.build_configuration }}" /p:platform="${{ matrix.build_platform }}" /p:PlatformToolset="v143"

    - name: Generate SHA256 hash for application_x64
      if: matrix.build_platform == 'x64' && matrix.build_configuration == 'Release'
      shell: pwsh
      run: |
        $hash = Get-FileHash -Path "bin64\StayAwake.exe" -Algorithm SHA256 | Select-Object -ExpandProperty Hash
        $lowHash = $hash.ToLower()
        echo "StayAwake.exe (64-bit) ===> SHA256 Hash: $lowHash"

    - name: Archive artifacts for x64
      if: matrix.build_platform == 'x64' && matrix.build_configuration == 'Release'
      uses: actions/upload-artifact@v4
      with:
          name: application_x64
          path: bin64\StayAwake.exe

    - name: Generate SHA256 hash for application_x86
      if: matrix.build_platform == 'Win32' && matrix.build_configuration == 'Release'
      shell: pwsh
      run: |
        $hash = Get-FileHash -Path "bin\StayAwake.exe" -Algorithm SHA256 | Select-Object -ExpandProperty Hash
        $lowHash = $hash.ToLower()
        echo "StayAwake.exe (32-bit) ===> SHA256 Hash: $lowHash"

    - name: Archive artifacts for Win32
      if: matrix.build_platform == 'Win32' && matrix.build_configuration == 'Release'
      uses: actions/upload-artifact@v4
      with:
          name: application_x86
          path: bin\StayAwake.exe
